on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [released]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
            GOARCH: amd64
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
            GOARCH: arm64
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix run --inputs-from . nixpkgs#skopeo -- login ghcr.io --username "$GITHUB_ACTOR" --password "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#push-container "ghcr.io/${GITHUB_REPOSITORY}@@unknown-digest@"
      - run: nix run .#push-container "ghcr.io/${GITHUB_REPOSITORY}:${TAG#v}-${GOARCH}"
        if: github.event_name == 'release'
        env:
          # TODO: multi-arch manifest
          TAG: ${{ github.event.release.tag_name }}
          GOARCH: ${{ matrix.GOARCH }}



