on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    env:
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: login
        run: nix run --inputs-from . nixpkgs#skopeo -- login --username "$GITHUB_ACTOR" --password "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#push-container
